const INCREASE_BY_1 = "INCREASE_BY_1";
const INCREASE_BY_5 = "INCREASE_BY_5";
const DECREASE_BY_1 = "DECREASE_BY_1";
const DECREASE_BY_5 = "DECREASE_BY_5";
const RESET = "RESET";

const SEND_MESSAGE = "SEND_MESSAGE";

module.exports = {
  INCREASE_BY_1,
  INCREASE_BY_5,
  DECREASE_BY_1,
  DECREASE_BY_5,
  RESET,
  SEND_MESSAGE,
};
